### ISSUE TITLE
[Feature] 동아리 상세 소개 페이지 UI 및 단과대 토글 버튼 구현

### ISSUE THREAD

**Issue by naraeng** [Clubber2024/Clubber-Client#11]
## 📝 기능 설명

동아리 개별 페이지 들어갔을 때 보여지는 소개 페이지 구현
메뉴바 단과대 옆에 아래로 향하는 삼각형 버튼 클릭 시, 단과대 목록을 볼 수 있는 토글 구현

## ✅ TODO

- [x] 동아리 개별 소개 페이지 UI
- [x] 소개 페이지 및 리뷰 페이지 클릭 시, focusing bar 구현
- [ ] 단과대 클릭 시, 토글 구현
- [ ] 토글 구현하면서 position 속성의 영향으로 반응형 동작 시, 단과대 텍스트가 이동하는 부분 보완

## 📚 ETC

<img width="689" alt="스크린샷 2024-04-15 오후 12 23 33" src="https://github.com/Clubber2024/Clubber-Client/assets/108282052/2f18d7bb-629d-47c8-8437-2d82c50b5ad3">

- 소개페이지 반응형 css만 조금 더 손보면 완료
- 상단 메뉴바 토글을 적용 시켰을 때, position 속성으로 인한 단과대 텍스트 고정이슈
