### ISSUE TITLE
[Feature] 동아리 단과대 페이지별 연결 및 추가 수정사안

### ISSUE THREAD

**Issue by Kangyeeun0** [Clubber2024/Clubber-Client#17]
## 📝 기능 설명

1.  [단과대 -> IT -> 써밋] 클릭 시 동아리 상세 페이지로 이동
-> 현재 test용으로, 써밋만 연결해놨음 (추후 다른 동아리 데이터 정리 후에 연결 예정)
2.  단과대 토글 에러 수정
3. 단과대 토글 닫힘 기능 추가
-> 화살표(토글 버튼) 클릭 시에만 토글이 아래로 펼쳐지고, 페이지가 새로고침될 때마다 토글 자동으로 닫힘 기능 추가
5. 메인 페이지 디자인 약간 수정 ( 공지사항 타이틀 )
6. 단과대(it) 클릭 시 나오는 페이지 디자인 수정 
7.  clubber 로고 클릭 시 메인 페이지로....
8.  처음 웹 들어갔을 때 헤더& 푸터만 뜸 -> 이 부분 수정 완료
-> 루트 경로를 메인 페이지(공지사항 및 rank)로 설정해놓음

## ✅ TODO

- [x] 단과대 및 중앙 동아리 클릭 시에 나오는 동아리 목록 페이지 디자인 수정
- [x]  단과대 및 중앙 동아리 상세 페이지 연결 다 완료 시키기
- [x] 단과대 토글 디자인 바꾸기!!

## 📚 ETC

![image](https://github.com/Clubber2024/Clubber-Client/assets/102957509/049fbe14-013a-47df-afc9-08d10029bc5a)
![image](https://github.com/Clubber2024/Clubber-Client/assets/102957509/f69dfd8c-96d3-46f7-99a8-625d667db2a0)
![image](https://github.com/Clubber2024/Clubber-Client/assets/102957509/b61b432c-490c-46e1-85d6-b2fce6e0a9fe)
![image](https://github.com/Clubber2024/Clubber-Client/assets/102957509/64eff532-39db-4393-8e35-68276ebd14b3)
