### ISSUE TITLE
[Refactor] 메인페이지 및 해시태그 수정

### ISSUE THREAD

**Issue by naraeng** [Clubber2024/Clubber-Client#19]
## 📝 리팩토링 설명

메인페이지 헤더와 해시태그 종류 수정

## ✅ TODO

- [ ] 헤더, 메뉴바 통합
- [ ] 해시태그 아이콘 및 종류 수정
- [ ] 공지사항 / 순위 ui 수정

## 📚 ETC

<img width="1440" alt="스크린샷 2024-05-15 오후 3 53 04" src="https://github.com/Clubber2024/Clubber-Client/assets/108282052/0058e084-e1f0-4e32-97b5-9064d60eb2ef">
