### ISSUE TITLE
[Feature] 메인페이지 공지사항, 조회수 api 연동

### ISSUE THREAD

**Issue by naraeng** [Clubber2024/Clubber-Client#28]
## 📝 기능 설명

메인페이지 공지사항, 조회수 api 연동

## ✅ TODO

- [x] 메인페이지 공지사항 api
- [x] 공지사항 양식에 맞게 보여주기
- [x] 메인페이지 조회수 api

## 📚 ETC

<img width="809" alt="스크린샷 2024-05-24 오후 4 58 16" src="https://github.com/Clubber2024/Clubber-Client/assets/108282052/811325f4-f77f-41bf-9bbb-b8e7631c2c6e">

**Comment by naraeng** [comment]
메인 공지사항 api 수정완료
