### ISSUE TITLE
[Feature]중앙동아리 UI 개발

### ISSUE THREAD

**Issue by Kangyeeun0** [Clubber2024/Clubber-Client#5]
## 📝 기능 설명

메뉴바에서 중앙 동아리 클릭 시 나타나는 페이지

## ✅ TODO

- [x] 디자인 확정 후 디자인 수정
- [x] 헤더, 푸터와 연결
- [x] 00동아리 클릭시 동아리 페이지로 넘어가는 기능 추가

## 📚 ETC

![image](https://github.com/Clubber2024/Clubber-Client/assets/102957509/761f53ea-5c27-4748-af0e-5b0c79cac7bc)
